### ISSUE TITLE
Feature Request: Toggle sound by one button press

### ISSUE THREAD

**Issue by tronta** [rafaelmardojai/blanket#145]
It would be great, if one could deactivate, activate (previous sound level) an individual sound by one click.

What about, if one clicks on the blue icon/pictogram it turns white again, with the slider still working and at the same position. And with an other click to turn it on again (turning blue).
When changing the slider, it gets active as well.

Imho, not sure, if the loud speaker symbol is really needed. The blue color of the icon nicely shows, that the sound is active.

**Comment by rafaelmardojai** [comment]
> Imho, not sure, if the loud speaker symbol is really needed. The blue color of the icon nicely shows, that the sound is active.

Right now in `master`, the sound icon is colored when the sound is "active" (the slider is > 0) and the speaker icon is shown when it's actually playing (the general volume isn't 0 and the sounds aren't paused).

About the request, an option to mute sounds seems interesting, but I'm curious about the use case, I guess it's that you can save your preferred volume level while playing other sounds. In `master` now we have the ability to save presets (#61) and that will probably satisfy better this use case.

**Comment by tronta** [comment]
The use case is probably, playing around and activate deactivate different sounds fast and simple, to try different combinations.
Currently one needs to slide it left and right. But usually, I just want to hear it. Making it softer or louder is for me fine tuning.

**Comment by rafaelmardojai** [comment]
Right, so activating a sounds that is deactivated (slider in 0), will activated it with the volume in let's say 50%?

**Comment by tronta** [comment]
The slider could be set (also for the muted sounds) initially to eg 50%, so it's not too confusing for the user, what will happen if he/she activates it. When having moved it, it would be great, if it can store its value.
So eg the user might want the thunderstorm louder than the river, and so he/she does not need to set this after every start.

**Comment by rafaelmardojai** [comment]
Correct. So sounds will save two values, **muted** and **volume**. When a sound is activated it toggles the muted state. If no saved volume exists (or is = 0%) when unmuted it set the volume to 50%.

That sounds fine?

**Comment by tronta** [comment]
Sounds great for me!

**Comment by tronta** [comment]
Not 100% sure about the discoverability that the icons can be clicked on. Maybe it would be better if they would have a button shape.

**Comment by rafaelmardojai** [comment]
Other option is to make the whole sound row clickable, through I don't think it helps in discoverability.

**Comment by rafaelmardojai** [comment]
This is what I have implemented for now:

https://user-images.githubusercontent.com/6210397/127430110-21e6392d-4ef3-4d8e-981f-3b5556813d7d.mp4

I'm still not sure if the activatable rows are enough discoverable.

**Comment by tronta** [comment]
That's already really cool.
What I really like about your app is its clean design.
And therefore I still think the loud speaker disturbs a little, especially as there is already the color available :smile: 

To the buttons: I guess if you sett the relief to half, it could be nice. And if the button is pressed, I guess it's clear enough, what's going on, and then no loud speaker is needed :smile:

**Comment by rafaelmardojai** [comment]
Yeah, I added the speaker icon when we hadn't the "colorable" icons and I have kept it because it's connected to the player backend playing state and helped me to solve some issues when the backend wasn't playing sync with the UI.

Now I will remove it or keep it behind some hidden setting for debug purposes.

**Comment by rafaelmardojai** [comment]
Also I should keep the speaker indicator for custom sounds, since them don't have an icon.

**Comment by tronta** [comment]
I would suggest to add an icon for custom sounds as well. Eg a loudspeaker or a notes, or so.
So there would be more or less consistent.
What do you think?

**Comment by rafaelmardojai** [comment]
They were like that before, they used this [sound wave icon](https://github.com/rafaelmardojai/blanket/blob/master/data/resources/icons/com.rafaelmardojai.Blanket-sound-wave-symbolic.svg), but I changed that in [cb40bf7278a2c24f9cfd0ed549d1981620306e6e] to implement a more compact design by GNOME designers recommendation and to avoid request like #64 because having various sounds together with the same icon looks odd. 

Maybe I could re-add the icon with a smaller size, or use a standard GNOME symbolic 16px icon. Although the speaker indicator doesn't look too odd in the custom audios context.

**Comment by tronta** [comment]
In my opinion not a lot of people will add many custom sounds, (But I can be of course wrong. That's what market studies and telemetry are there for :smile: ) And those icons are really pretty,
I personally would prefer consistency over compactness.
And the request https://github.com/rafaelmardojai/blanket/issues/64 is about a custom icon, so no contradiction, quite the opposite.

And I totally agree keeping the app as simple as possible. It should not become an Outlook 2.0.
If some one wants to adds 10 custom sounds or more, one should probably search for an other solution :laughing:

**Comment by rafaelmardojai** [comment]
>  And the request #64 is about a custom icon, so no contradiction, quite the opposite.

Yeah, I meant that #64 is a fair request to mitigate the fact that various sounds with the same icon look odd, but that will add too much unneeded complexity.

> Maybe a compromise solution could be to use different colors for the custom icons, so you could circle through 10 colors or so, for the high end users … and one can still that the cows were on green or so…

Do you mean different colors when active? In any case probably different colors might be a bit complex, it will need different colors for light/dark mode, we already have a poor contrast with the blue color in dark mode.

Well for now I will keep the implementation as you seen in the video. I will try to improve discoverability as a follow-up. I'm not sure if making the rows look more "clickable" will result strange with the regular GNOME lists design. Maybe a "tips" dialog in first launch could help to make more discoverable some features.

About the custom sounds, I agree that currently they don't look too good, I will try to look some solution or otherwise just add the  sound wave icon again. I also don't think that users add a lot of sounds.

**Comment by tronta** [comment]
Btw thanks for your effort and your great app.
