### ISSUE TITLE
Change train sound to comply with DFSG

### ISSUE THREAD

**Issue by werdahias** [rafaelmardojai/blanket#297]
I am in the process of creating an official debian package. The sounds_licensing states that the train sound is by vahid and licensed under the CC sampler license. The link for the train sounds just redirects to another sound using that train sound among other. Do you have the original source for this sound by any change ?

**Comment by rafaelmardojai** [comment]
Hey @haggen88 you sent the extracted version of Train by Vahid from https://trains.ambient-mixer.com/rainy-train here: https://github.com/rafaelmardojai/blanket/issues/46#issuecomment-695197976. By any chance you know any live source?

**Comment by haggen88** [comment]
That audio came from that [source](https://xml.ambient-mixer.com/audio/4/8/e/48eec7476e451ea78a70bbcf8c5f91a8.ogg)... I have no idea where the original is. I tried to look it up on freesound.org but the audio is not there.

**Comment by rafaelmardojai** [comment]
Right, that's what supposed, also tried to search on the web but nothing.

So yeah @werdahias, [this](https://trains.ambient-mixer.com/rainy-train) is the only source we have for that sound's author and license.

**Comment by werdahias** [comment]
Ok, thanks. I hope this wiil do as copyright information. Can I leave this open for now until the debian package gets reviewed? It might take a month.

**Comment by werdahias** [comment]
@rafaelmardojai  thanks for the info. Unfortunately, debian considers the CC sampling license [non-free](https://wiki.debian.org/DFSGLicenses?action=show&redirect=Licenses#Creative_Commons_Sampling_Plus_.28CC_SAMPLING.2B-.29_1.0). Could you maybe use a different train sound licensed under CC0 or CC-BY ? [This](https://freesound.org/people/felix.blume/sounds/166086/) looks like a candidate at 00:35

**Comment by werdahias** [comment]
hi, any update ?

**Comment by haggen88** [comment]
It is difficult to find audio samples that contain the characteristic sound of the train passing through the railway tracks [clickety-clack], the candidates I found were loops of a couple of seconds.

@rafaelmardojai  luckily i think i found a loop that could be used
-  'Trains of the Yamanote Line' by SDLx     [CC BY 3.0]   [SDLx - Trains of the Yamanote Line.ogg.zip](https://github.com/rafaelmardojai/blanket/files/11436739/SDLx.-.Trains.of.the.Yamanote.Line.ogg.zip)
  from https://freesound.org/people/SDLx/sounds/259988/

I don't know how to perform a LUFS analysis [I'll leave that to @Porrumentzio], the closest I got is to edit the loop with Audacity and check how it turned out with Loudness Normalization [Effect menu [-35]] and it seems more acceptable:
[norm lufs SDLx - Trains of the Yamanote Line.ogg.zip](https://github.com/rafaelmardojai/blanket/files/11436837/norm.lufs.SDLx.-.Trains.of.the.Yamanote.Line.ogg.zip)

**Comment by werdahias** [comment]
@haggen88  thanks for looking into that :) With car ride do you mean the city sounds ?

**Comment by haggen88** [comment]
I mean #189

**Comment by werdahias** [comment]
ah, right, my bad

**Comment by rafaelmardojai** [comment]
@haggen88 IMO is too short, but is the best that we have, and I think is important to avoid the CC sampling license. So I will include that sound.

**Comment by werdahias** [comment]
thanks !
